### ISSUE TITLE
x509: certificate is valid for 127.0.0.1, 10.0.2.15, not 192.168.59.105

### ISSUE THREAD

**Issue by damnhandy** [boot2docker/osx-installer#119] opened 2015-07-08 11:49 UTC
I am getting the following error when I restart boot2docker and run any docker command:

```
$ docker images
An error occurred trying to connect: Get https://192.168.59.105:2376/v1.19/images/json: x509: certificate is valid for 127.0.0.1, 10.0.2.15, not 192.168.59.105
```

The only fix right now to is to delete the ISO and rerun `boot2docker init`, which is costly and slow when riding on the MBTA :) Not to mention, I it requires a full rebuild of all of the images I'm working on.

**Comment by dimio111** [comment] 2015-07-09 05:51
I am having this problem as well.
Every tine i restart boot2docker 1.7 on mac i am getting:
An error occurred trying to connect: Get https://192.168.59.103:2376/v1.19/containers/json: x509: certificate is valid for 127.0.0.1, 10.0.2.15, not 192.168.59.103

Al my colleges i know of are having the same problem.

**Comment by bfagundez** [comment] 2015-07-11 01:22
Try running 
```
boot2docker delete
boot2docker init
boot2docker down
boot2docker up
```
I was having the same problem after 1.7 upgrade and worked after the delete/init

**Comment by robsaunders** [comment] 2015-07-11 08:10
I keep reading this 'solution' over and over of nuking your images and re-doing it all. This kind of makes docker useless... is there any info out there either on what's causing this or when/how it can be fixed/patched?

I hate being 'that guy' to complain but I don't really understand how such an obviously far-reaching bug has been in the main source release for so long now. Perhaps there's something wrong with the development process the boot2docker team is using because to me ... well I'm off investigating vagrant even though it doesn't solve my needs.

Perhaps someone in the Docker team can point the community to why this might be happening so someone can try to patch it? Every thread is just showing this awful workaround which is not even close to a solution or explanation.

**Comment by bfagundez** [comment] 2015-07-11 15:24
@robsaunders, I agree, this needs to be examined.

**Comment by mygoare** [comment] 2015-07-11 18:49
+1

**Comment by damnhandy** [comment] 2015-07-12 13:00
This is actually not specific to OS X and is being tracked here:

https://github.com/boot2docker/boot2docker/issues/968

I have been seeing the same thing on Windows 7 Enterprise as well. My solution has been rolling back to 1.6.2 until a patch for 1.7 is released. 

This issue should probably be marked as a dupe of 968.

**Comment by Priyanky** [comment] 2015-07-14 09:24
+1

**Comment by caledhwa** [comment] 2015-07-14 17:04
+1

**Comment by damnhandy** [comment] 2015-07-15 12:02
This seems to be fixed in 1.7.1. I can stop and restart boot2docker and I get no error about the certificates and the IP doesn't change either.

**Comment by jangalinski** [comment] 2015-07-16 07:39
Seems to be fixed with 1.7.1 -> close?

**Comment by carlossg** [comment] 2015-07-16 14:38
this is a dupe of #938, fixed in 1.7.1

**Comment by geronimo-iia** [comment] 2015-07-16 18:49
1.7.1 fixed this issue for me

**Comment by dimio111** [comment] 2015-07-17 07:50
Fixed for me to, but i had to delete the boot2docker iso file manually?

**Comment by fordlee404** [comment] 2015-07-17 12:22
@dimio111 you can update the boot2docker with command `boot2docker upgrade`

**Comment by innokenty-shuvalov** [comment] 2015-07-22 13:37
I do confirm a single ```boot2docker upgrade``` to 1.7.1 fixes the issue.

**Comment by indiedotkim** [comment] 2015-07-22 13:52
I am at 1.7.1 and still have that issue. I am going through the delete/init/up cycle as described by @bfagundez as workaround every now and then.

**Comment by fordlee404** [comment] 2015-07-23 00:43
@indiedotkim try this to solve the problem
```
$ boot2docker ssh
$ sudo /etc/init.d/docker stop
$ sudo /etc/init.d/docker start
```
and you will not lose your images and containers.

**Comment by indiedotkim** [comment] 2015-07-23 01:34
@fordlee404 Not seeing the errors anymore -- I hope it stays this way. Thank you!

**Comment by rnoska** [comment] 2015-07-23 23:59
@fordlee404 - Thanks for posting.  Restarting docker worked for me.

**Comment by pejvan** [comment] 2015-07-24 14:14
unfortunately, the error still exists for me:
```
pejvan$ boot2docker status
running
pejvan$ $(boot2docker shellinit)
Writing /Users/pejvan/.boot2docker/certs/boot2docker-vm/ca.pem
Writing /Users/pejvan/.boot2docker/certs/boot2docker-vm/cert.pem
Writing /Users/pejvan/.boot2docker/certs/boot2docker-vm/key.pem
Your environment variables are already set correctly.
pejvan$ boot2docker status
running
pejvan$ docker ps -a
An error occurred trying to connect: Get https://192.168.59.103:2376/v1.19/containers/json?all=1: x509: certificate is valid for 127.0.0.1, 10.0.2.15, not 192.168.59.103
```

indeed, stopping and restarting the service inside the vm solves the problem -- though all the running containers are obviously stopped.

**Comment by tjgillies** [comment] 2015-07-25 06:07
Upgrade fixed for me

**Comment by CocaCola183** [comment] 2015-07-27 10:09
@bfagundez I fix the problem in you way, thx

**Comment by jacobtomlinson** [comment] 2015-07-28 09:36
Looks like the upgrade worked for me too :+1:

**Comment by olalonde** [comment] 2015-08-03 14:00
`boot2docker upgrade` also worked here.

**Comment by bowlofstew** [comment] 2015-08-03 15:58
Worked for me as well, thanks!

**Comment by huseyinbabal** [comment] 2015-08-14 06:10
@bfagundez worked for me, thanks!

**Comment by JonathanRosado** [comment] 2016-05-05 01:57
experiencing this bug docker 1.11

**Comment by tianon** [comment] 2018-02-26 23:35
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).

**Closed by tianon** 2018-02-26 23:35 UTC
